name = "trashmysite"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat" ]

account_id = "0e405dda228e3448f1366acb0bc341ef"
workers_dev = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'trashmysite'
preview_bucket_name = 'trashmysite'
